import Vue from 'vue'
import {
  Aside,
  Main,
  Card,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Container,
  Button,
  Pagination,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  TabPane,
  Tabs,
  Input,
  Breadcrumb,
  BreadcrumbItem
} from 'element-ui'
Vue.use(Aside)
Vue.use(Main)
Vue.use(Card)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Container)
Vue.use(Button)
Vue.use(Pagination)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(TabPane)
Vue.use(Tabs)
Vue.use(Input)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
