import Vue from 'vue'
import {
  Aside,
  Main,
  Card,
  Menu,
  MenuItem,
  MenuItemGroup,
  Submenu,
  Container,
  Button,
  Pagination,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  TabPane,
  Input,
  Tabs,
  Select,
  Option,
  Table,
  TableColumn,
  Loading,
  Link,
  Breadcrumb,
  BreadcrumbItem,
  Dialog,
  RadioGroup,
  RadioButton
} from 'element-ui'
Vue.use(Aside)
Vue.use(Main)
Vue.use(Card)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Container)
Vue.use(Button)
Vue.use(Pagination)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(TabPane)
Vue.use(Input)
Vue.use(Tabs)
Vue.use(Select)
Vue.use(Option)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Loading)
Vue.use(Link)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Dialog)
Vue.use(RadioGroup)
Vue.use(RadioButton)
