import Vue from 'vue'
import {
  Aside,
  Main,
  Card,
  Menu,
  MenuItem,
  Container,
  TabPane,
  Tabs,
  Button,
  Input,
  Row,
  Col,
  Table,
  TableColumn,
  Pagination,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Tree,
  Cascader,
  Calendar,
  Dialog,
  Drawer,
  Tag,
  Message,
  Submenu,
  Progress,
  Loading,
  Select,
  Option,
  Popover,
  Breadcrumb,
  BreadcrumbItem,
  DatePicker,
  ButtonGroup,
  Image,
  Checkbox,
  Tooltip,
  Badge
} from 'element-ui'
Vue.use(Aside)
Vue.use(Main)
Vue.use(Card)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Container)
Vue.use(TabPane)
Vue.use(Tabs)
Vue.use(Button)
Vue.use(Input)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Tree)
Vue.use(Cascader)
Vue.use(Calendar)
Vue.use(Dialog)
Vue.use(Drawer)
Vue.use(Tag)
Vue.use(Progress)
Vue.use(Loading)
Vue.use(Select)
Vue.use(Option)
Vue.use(Popover)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(DatePicker)
Vue.use(ButtonGroup)
Vue.use(Checkbox)
Vue.use(Image)
Vue.use(Tooltip)
Vue.use(Badge)
// Vue.use(Message)

Vue.prototype.$message = Message
